export const images = {
  logo: require("../assets/icons/Logo (1).svg").default,
  home: require("../assets/icons/home.svg").default,
  hamburger: require("../assets/icons/hamburger.svg").default,
  square: require("../assets/icons/square.png"),
  events: require("../assets/icons/events.svg").default,
  speakers: require("../assets/icons/speakers.svg").default,
  report: require("../assets/icons/report.svg").default,
  profile: require("../assets/icons/profile.svg").default,
  bell: require("../assets/icons/bell (1).svg").default,
  messages: require("../assets/icons/messages.svg").default,
  settings: require("../assets/icons/settings-2.svg").default,
  collapersleft: require("../assets/icons/collapersleft.svg").default,
  collapersRight: require("../assets/icons/collapersRight.svg").default,
  avatar: require("../assets/icons/Avatar Fill.svg").default,
  info: require("../assets/icons/information.svg").default,
  upArrow: require("../assets/icons/arrow-up-right.svg").default,
  downArrow: require("../assets/icons/arrow-down-right.svg").default,
  search: require("../assets/icons/search.svg").default,
  export: require("../assets/icons/export.svg").default,
  dotVertical: require("../assets/icons/dots-vertical.svg").default,
  exportWhite: require("../assets/icons/exportwhite.svg").default,
  dotVerticalWhite: require("../assets/icons/dots-vertical-white.svg").default,
  close: require("../assets/icons/close.svg").default,
  aavatar: require("../assets/icons/Avatar.svg").default,
  chevronRight: require("../assets/icons/chevron-right.svg").default,
  chevronDown: require("../assets/icons/chevron-down.svg").default,
  chevronRightWhite: require("../assets/icons/chevron-rightWhite.svg").default,
  chevronDownWhite: require("../assets/icons/chevron-downWhite.svg").default,
  leftpagination: require("../assets/icons/leftpagination.svg").default,
  rightpagination: require("../assets/icons/rightpagination.svg").default,
};